Repository googleapis/java-language, pull requests merged in 2020-06, with the labels that each got.

#153 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#156 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#158 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#160 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#165 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#170 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#175 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#176 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-language/pom.xml
  grpc-google-cloud-language-v1/pom.xml
  grpc-google-cloud-language-v1beta2/pom.xml
  pom.xml
  proto-google-cloud-language-v1/pom.xml
  proto-google-cloud-language-v1beta2/pom.xml
Labels: cla: yes

#184 chore: remove clirr ignored differences after 1.99.3
  grpc-google-cloud-language-v1/clirr-ignored-differences.xml
  grpc-google-cloud-language-v1beta2/clirr-ignored-differences.xml
Labels: cla: yes

#186 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
