Repository googleapis/java-language, pull requests merged in 2020-08, with the labels that each got.

#197 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /language/cloud-client
  samples/snippets/src/main/java/com/example/language/QuickstartSample.java
  samples/snippets/src/main/java/com/example/language/SetEndpoint.java
  samples/snippets/src/test/java/com/example/language/QuickstartSampleIT.java
  samples/snippets/src/test/java/com/example/language/SetEndpointIT.java
Labels: cla: yes

#198 chore: regenerate README samples
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#196 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#200 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#205 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#210 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#211 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: language, cla: yes, context: full

#212 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
