Repository googleapis/java-language, pull requests merged in 2020-09, with the labels that each got.

#218 chore: regenerate README
  README.md
  synth.metadata
Labels: api: language, cla: yes, context: none

#220 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#234 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#237 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#236 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: language, automerge, cla: yes

#244 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#246 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
