Repository googleapis/java-language, pull requests merged in 2021-09, with the labels that each got.

#671 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: language, automerge

#711 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: language, automerge

#715 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, api: language, automerge

#729 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: language, automerge

#721 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  README.md
  renovate.json
Labels: cla: yes, api: language
