Repository googleapis/java-language, pull requests merged in 2021-05, with the labels that each got.

#448 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: language, automerge, cla: yes, context: none

#449 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: language, automerge, cla: yes

#454 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: language, automerge, cla: yes

#455 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: language, automerge, cla: yes, context: full

#460 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: language, automerge, cla: yes

#461 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: language, automerge, cla: yes, context: full

#464 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: language, automerge, cla: yes, context: full

#462 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-language-bom/pom.xml
  google-cloud-language/pom.xml
  owlbot.py
  pom.xml
  versions.txt
Labels: api: language, automerge, cla: yes

#470 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: language, automerge, cla: yes
